server:
  port: 9091

spring:
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 29000
      username: java12user
      password: root
      database: userDb

    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/UserDb
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

jwt:
  secretKey: ${java12secret}
  issuer: ${java12issuer}
rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  register-bindingKey: registerBindingKey

  active-status-queue: activeStatusQueue
  active-status-bindingKey: activeStatusBindingKey

  register-elastic-queue: registerElasticQueue
  register-elastic-bindingKey: registerElasticBindingKey
  user-exchange: exchangeUser